### ISSUE TITLE
deprecation warnings in  0.5.0-dev+4402 (Win64)

### ISSUE THREAD

**Issue by PaulSoderlind** [amitmurthy/LibExpat.jl#44]
Hi,
the package seems to generate lots of warning messages in  0.5.0-dev+4402 (Win64), for instance, things like this:

WARNING: bytestring(p::Union{Ptr{Int8},Ptr{UInt8}}) is deprecated, use String(p) instead.
in depwarn(::String, ::Symbol) at .\deprecated.jl:64
in bytestring(::Ptr{UInt8}) at .\deprecated.jl:50
in end_element(::Ptr{Void}, ::Ptr{UInt8}) at C:\Users\psoderlind.julia\v0.5\LibExpat\src\LibExpat.jl:

/Paul S

**Comment by nalimilan** [comment]
I think this was fixed by https://github.com/amitmurthy/LibExpat.jl/pull/45.

**Comment by tkelman** [comment]
fixed on master
