### ISSUE TITLE
Cannot build LibExpat on Windows Julia 0.6.0-dev

### ISSUE THREAD

**Issue by galenlynch** [amitmurthy/LibExpat.jl#54]
When I try to build my project on WIndows with `0.6.0-dev`, `WinRPM` fails to build due to `LibExpat`:

```
LoadError: LoadError: LoadError: LoadError: syntax: expected identifier after "const"
while loading C:\Users\appveyor\.julia\v0.6\LibExpat\src\lX_common_h.jl, in expression starting on line 14
while loading C:\Users\appveyor\.julia\v0.6\LibExpat\src\LibExpat.jl, in expression starting on line 13
while loading C:\Users\appveyor\.julia\v0.6\WinRPM\src\WinRPM.jl, in expression starting on line 11
while loading C:\Users\appveyor\.julia\v0.6\WinRPM\deps\build.jl, in expression starting on line 1
```

The full error message can be found [here](https://ci.appveyor.com/project/galenlynch/openephysloader-jl/build/job/b4v3pbqxo808ylg6), however I can reproduce this problem by trying to add `WinRPM` by itself.

**Comment by musm** [comment]
SHould be fixed by https://github.com/amitmurthy/LibExpat.jl/pull/56

can you check please?

**Comment by galenlynch** [comment]
It works now, thanks!
